services:
  redis:
    image: redis:latest
    container_name: authly-redis-c
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  backend:
    build: ./backend
    image: authly-backend-i:1.0
    env_file:
      - backend/.env
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
    container_name: authly-backend-c
    depends_on:
      - redis
    command: bun run dev
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json

volumes:
  redis_data:
    driver: local