services:
  backend:
    build: ./backend
    image: authly-backend-i:1.0
    env_file:
      - backend/.env
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
    container_name: authly-backend-c
    command: bun run dev
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json